/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vip_frendy_opencv_OpenCVManager */

#ifndef _Included_vip_frendy_opencv_OpenCVManager
#define _Included_vip_frendy_opencv_OpenCVManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vip_frendy_opencv_OpenCVManager
 * Method:    toBW
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_vip_frendy_opencv_OpenCVManager_toBW
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
